### ISSUE TITLE
カーソルについて

### ISSUE THREAD

**Issue by itchyny** [rbtnn/pipe.vim#1]
ゲーム中、カーソルが常に左上にあるのが気になるので、次のいずれかを実装すると見栄えが良いと思います。
 1. ゲーム中はカーソルを一時的に消す
 2. 選択中のブロックの左上あるいは右下にカーソルを移動する

カーソルを消す方法は https://github.com/osyo-manga/vital-over/blob/master/autoload/vital/__latest__/Over/Commandline/Base.vim#L289-L312 が参考になると思います。
(他のゲームについても言えることなので、game_engine.vimで対応できることかもしれません)

**Comment by rbtnn** [comment]
確かにそうですね。game_engine.vim側で対応しておきます。
ご報告ありがとうございました。
